export const enviroment = {
  production: false,
  server: 'staging',
  // For production uncomment this
  // apiUrl: window.location.protocol + '//' +window.location.hostname+'/v1/',
  // symfonyHost: window.location.protocol + '//' +window.location.hostname+'/',
  // symfonyDomain: window.location.hostname,
  // MAP_API:"AIzaSyA62YEg0WsS6u8nsrAvjafM8SRNznNBYJk",
  apiUrl: 'https://newtest.classcare.in/v1/',
  newApiUrl: 'https://newtest.classcare.in',
  // apiUrl: 'http://127.0.0.1:8000/v1/',
  // newApiUrl : 'http://127.0.0.1:8000',
  symfonyHost: 'https://newtest.classcare.in/',
  symfonyDomain: 'newtest.classcare.in',
  bugsnugApiKey: '5de9f606db359cbf7dcc43a68baccd9c',
  //laravel socket
  broadcaster: 'pusher',
  key: 'abcdefg',
  // wsHost: '127.0.0.1',
  wsHost: 'superadmindev.classcare.in',
  wsPort: 6001,
  forceTLS: false,
  disableStats: true,
  authEndpoint : window.location.protocol + '//' +window.location.hostname.split('.')[0]+'.'+window.location.hostname.split('.')[1]+'.'+window.location.hostname.split('.')[2]+'/v1/api/broadcasting/auth',
  token: 'Bearer '+localStorage.getItem('token'),
  s3BucketUrl : 'https://classcare.ap-south-1.linodeobjects.com',
  whatsappClientId: '866236359019245',
  domainName: 'http://localhost:4200/app',
  fabAppId: '866236359019245',
  fabConfigId : '1321990742260723',
  fabVersion : 'v21.0',
  whatsappClientSecret: '',
  recaptchaSiteKey : '6LcH1wwrAAAAAPjSuW2z77R3vUNaU3BPG3J_PDmq'
}