const columns = {
    'Class Name' : 'class_name',
    'Batch Name' : 'batch_name',
    "First Name" : 'first_name',
    "Middle Name" : 'middle_name',
    "Last Name" : 'last_name',
    "First Name(Secondary)" : 'secondary_first_name',
    "Middle Name(Secondary)" : 'secondary_middle_name',
    "Last Name(Secondary)" : 'secondary_last_name',
    "Date of Birth" : 'date_of_birth',
    "Age" : 'age',
    "Account Created" : 'create_at',
    "GR Number / Student Id" : 'studentId',
    "Mother Name" : 'mother_name',
    "Father Name" : 'father_name',
    "Birth Place" : 'birthPlace',
    "Birth Taluka"  :  'birth_taluka',
    "Birth District"  :  'birth_district',
    "Cast"  :  'cast',
    "Sub Cast"  :  'sub_cast',
    "Categories" : 'categories',
    "Leaving Date" : 'leaving_date',
    "Email" : 'email',
    "Gender" : 'gender',
    "Roll Number" : 'rollno',
    "Username" : 'username',
    "Password" : 'password',
    "Phone Number" : 'phone_number',
    "Aadhar Number" : 'adhaar_number',
    "Apaar Id" : 'apaar_id',
    "Mother Occupation" : 'mother_occupation',
    "Father Occupation" : 'father_occupation',
    "Father Number" : 'father_number',
    "Mother Number" : 'mother_number',
    "Father Education"  :  'father_education',
    "Mother Education"  :  'mother_education',
    "Bank Name"  :  'bankname',
    "Branch IFSC"  :  'branchifsc',
    "Account Number"  :  'accountnumber',
    "IFSC Code"  : 'ifsccode',
    "SMS Number" : 'send_sms_number',
    "Parent Whatsapp Number" : 'parentWhatsappNo',
    "Student Whatsapp No" : 'studentWhatsappNo',
    "Parent Email" : 'parentEmail',
    "Status" : 'status',
    "UID No" : 'uidNo',
    "Religion" : 'religion',
    "Nationality" : 'nationality',
    "Working Days School" : 'working_days_school',
    "Reason Leaving School" : 'reason_leaving_school',
    "Type Of Old School"  :  'type_of_old_school',
    "Last Examination Result" : 'result_last_examination',
    "Address" : 'address',
    "School" : 'school',
    "Right to Education" : 'rightToEducation',
    "Old or New" : 'old_new',
    "Parmanent Address" : 'permanentAddress',
    "Current City" : 'currentCity',
    "Parmanent City" : 'permanentCity',
    "Hometown" : 'hometown',
    "Blood Group" : 'bloodGroup',
    "Sibling Information" : 'siblingInfo',
    "Student Display Name" : 'student_display_name',
    "Secondary First Name" : 'secondary_first_name',
    "Secondary Middle Name" : 'secondary_middle_name',
    "Secondary Last Name" : 'secondary_last_name',
    "Admission date" : 'admission_date',
    "Admission year" : 'admission_year',
    "Adhaar Number" : 'adhaar_number',
    "Previous school category" : "previous_school_category",
    "Previous school city/village" : "previous_school_city_village",
    "Remark" : "remark",
    "Pen No" : "pen_no",
    "Height" : "height",
    "Height Type" : "height_type",
    "Weight" : "weight",
    "EWS" : "ews",
    "Section Name" : "section_name",
    "UUID" : "UUID",
    "Hall Ticket/SID Number" : "hall_ticket_sid_number"
};

export default columns